version: "2"
services:
  penpal-frontend:
    build: ./PenPal
    volumes:
      - penpal-npm-cache:/home/node/.npm
    ports:
      - "3000:3000"
    command: npm run dev-serve-frontend
    networks:
      - public

  penpal-server:
    build: ./PenPal
    volumes:
      - penpal-npm-cache:/home/node/.npm
    ports:
      - "3000:3000"
    command: npm run dev-run-server
    networks:
      - public

  node-red:
    image: nodered/node-red
    volumes:
      - node-red-data:/data
    ports:
      - "1880:1880"

volumes:
  penpal-npm-cache:
    external: false
  node-red-data:
    external: false

networks:
  public:
    driver: bridge
