version: "2"
services:
  penpal-frontend:
    volumes:
      - ./PenPal/app/src/:/penpal/app/src
      - ./PenPal/app/static/:/penpal/app/static
      - ./PenPal/app/package-frontend.json:/penpal/app/package.json
      - ./PenPal/app/webpack.config.js:/penpal/app/webpack.config.js
      - ./Plugins/:/penpal/plugins
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}

  penpal-server:
    volumes:
      - ./PenPal/app/src/:/penpal/app/src
      - ./PenPal/app/.babelrc:/penpal/app/.babelrc
      - ./PenPal/app/nodemon.config.json:/penpal/app/nodemon.config.json
      - ./PenPal/app/package-server.json:/penpal/app/package.json
      - ./Plugins/:/penpal/plugins:consistent
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
