version: "2"
services:
  penpal-base:
    build: ./PenPal
    image: penpal/base
    pull_policy: never

  penpal-frontend:
    build:
      context: ./PenPal
      dockerfile: ./Dockerfile-frontend
    pull_policy: never
    volumes:
      - penpal-frontend-npm-cache:/home/node/.npm
    ports:
      - "3000:3000"
    command: npm run frontend
    networks:
      - penpal

  penpal-server:
    build:
      context: ./PenPal
      dockerfile: ./Dockerfile-server
    pull_policy: never
    volumes:
      - penpal-server-npm-cache:/home/node/.npm
      - ./docker-compose.common.yaml:/penpal/app/docker-compose.common.yaml
    ports:
      - "3001:3001"
    command: npm run server
    networks:
      - penpal

  node-red:
    image: nodered/node-red
    volumes:
      - node-red-data:/data
    ports:
      - "1880:1880"

volumes:
  penpal-frontend-npm-cache:
    external: false
  penpal-server-npm-cache:
    external: false
  node-red-data:
    external: false

networks:
  penpal:
    driver: bridge
